### ISSUE TITLE
Test stuck on "initiating resources" -- doesnt complete

### ISSUE THREAD

**Issue by rp-andre** [Sitecore/Sitecore-Diagnostics-Toolset#2]
Having an issue on Server 2012 R2 where the test doesn't complete, and it appears to be stuck on "initiating resources"  This is consistent for multiple servers and generates the error below. Any ideas?

ERROR:
INFO An unhandled error occurred during preparing tests queue
System.InvalidOperationException: Something is wrong with configuration
at Sitecore.Diagnostics.Base.Assert.IsTrue(Boolean assertionCondition, String

**Comment by AlenPelin** [comment]
@rp-andre could you provide the entire log files from `%APPDATA%\Sitecore\Sitecore Diagnostics Toolset` folder?

**Comment by AlenPelin** [comment]
Actually, could you try the [latest QA version](http://dl.sitecore.net/updater/qa/sdt) first and after testing provide a log files?

**Comment by rp-andre** [comment]
I will give the QA version a run and report back shortly. Thanks!

**Comment by AlenPelin** [comment]
I've identified that the last QA version doesn't run in certain environments, so if it doesn't run in yours just please provide the already existing log files.

**Comment by rp-andre** [comment]
Using the QA version on Windows Server 2012 R2 does not launch, and the program crashes immediately. I have attached the complete log for review. Thank you for the assistance!

[log.20160308.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Toolset/files/164386/log.20160308.txt)

**Comment by AlenPelin** [comment]
@rp-andre It seems that Diagnostics Toolset cannot connect to dl.sitecore.net to download latest information about Sitecore releases:
```
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
```

And it looks like something is wrong with log files of your website - please check that the `<setting name="LogFolder" ... />` setting points to the real physical location in the `/sitecore/admin/showconfig.aspx` page output.

**Comment by rp-andre** [comment]
ok, i will look at this immediately and respond back. Appreciate it! Please stand by!

**Comment by rp-andre** [comment]
@AlenPelin what is the complete URL for dl.sitecore.net?
Even on my local machine, I receive the same as on the servers, which is a 403 forbidden. (When going to: dl.sitecore.net)

**Comment by AlenPelin** [comment]
The 403 forbidden is expected which means the request reached the server. The full URLs are:
```
http://dl.sitecore.net/updater/1.1/sdt/latest-version.txt
http://dl.sitecore.net/updater/info/v3/index.json
http://dl.sitecore.net/updater/info/v3/**
```

**Comment by rp-andre** [comment]
@AlenPelin can you please tell me the path to the logfolder setting file?

**Comment by AlenPelin** [comment]
@rp-andre open `/sitecore/admin/showconfig.aspx`, find there the setting and look at patch:source attribute value.

**Comment by rp-andre** [comment]
ok, not able to login to showconfig.aspx just yet, but will move forward on that tomorrow and update this thread. Appreciate the help.

Also, i am able to browse 2 of the 3 URLs above from the server. The index.json URL will not launch and prompts to save the file currently. I will also look into resolving that to display in the browser, if that is what is needed?

**Comment by AlenPelin** [comment]
The application doesn't care of your browser settings :sunglasses: it only should be able to download the appropriate resource on your web server itself.

**Comment by rp-andre** [comment]
@AlenPelin So in looking into /sitecore/admin/showconfig.aspx, I found 100+ settings for patch:source. Is there a more specifc attribute I can search for in this XML?

**Comment by rp-andre** [comment]
Additionally, here is the value I found in the showconfig.aspx file:
**<setting value="D:\inetpub\wwwroot\UAL\Data/logs" name="LogFolder"/>**

I also went onto the filesystem and verified this path does exists.

**Comment by AlenPelin** [comment]
@rp-andre latest QA version is working now (1.1.0.792) so could you try to reproduce the issue there? If still reproducible, please provide latest log file. Thanks.

**Comment by rp-andre** [comment]
@AlenPelin I just installed the latest version from the QA site, which is 1.1.0.793.
This was able to open on the server now, but remains at "Initializing Resources" as before.

Complete log file is attached for review and support. Thanks!

[log.20160309.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Toolset/files/166541/log.20160309.txt)

**Comment by AlenPelin** [comment]
It looks like your configuration is corrupted. It cannot find two following nodes:
```
/configuration/sitecore/settings/setting[@name='LogFolder']
/configuration/connectionStrings
```
Please attach the output of the `/sitecore/admin/showconfig.aspx` page.

**Comment by rp-andre** [comment]
Thanks @AlenPelin, I waited at least 2 minutes to give enough time. I will attach the output of the /sitecore/admin/showconfig.aspx momentarily.

**Comment by rp-andre** [comment]
Here is the showconfig.aspx XML data. Renamed to .txt

[ShowConfig.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Toolset/files/167398/ShowConfig.txt)

**Comment by rp-andre** [comment]
Also, where specifically do I find the following items you mentioned below:

/configuration/sitecore/settings/setting[@name='LogFolder']
/configuration/connectionStrings

**Comment by AlenPelin** [comment]
This is very strange. Could you try to run [SSPG](http://dl.sitecore.net/updater/sspg.html) with defaults and attach here?

**Comment by rp-andre** [comment]
Here you go. I appreciate the help and am really trying to get this Diagnostics tool to run ASAP so i can provide useful information to my client. Any support you can provide, is much appreciated and I am available to discuss as needed as well.

[scsupport_UAL_20160310.zip](https://github.com/Sitecore/Sitecore-Diagnostics-Toolset/files/168433/scsupport_UAL_20160310.zip)

**Comment by rp-andre** [comment]
@AlenPelin -- As additional information... when I run the Diag Toolset, and on the 2nd screen click on "Review associated resources", the program force closes every time (screenshot attached). I feel there could be something with how the application is looking for resources hanging it up and if you could determine the cause of this issue, it may be successful

![image](https://cloud.githubusercontent.com/assets/17729417/13693352/062e79a0-e710-11e5-95d6-1649fd0cc157.png)

**Comment by AlenPelin** [comment]
This line in web.config was the cause of the issue:
```
<location inheritInChildApplications="false">
```
It is not supported at the moment.

**Comment by rp-andre** [comment]
Thank you @AlenPelin. Is it safe to completely remove this line without impact to the application and try  again?

**Comment by AlenPelin** [comment]
@rp-andre I am trying to make it partially supported, hang on.

**Comment by rp-andre** [comment]
Thank you @AlenPelin

**Comment by AlenPelin** [comment]
@rp-andre try latest QA build, it is 1.1.0.803 now.

**Comment by rp-andre** [comment]
@AlenPelin This still did not work, but i believe the issue may be caused by an IIS service application that is hosted under the main sitecore site. What are your thoughts on that?

I am working on attempting to remove the application temporarily, then trying again soon.

**Comment by AlenPelin** [comment]
Fresh log files please :)

**Comment by rp-andre** [comment]
Hi @AlenPelin. So i narrowed the issue down to the web.config file.
If i have a default web.config file, the test will run just fine. so, its likely the structure of where entries lay in the web.config file with loading the sitecore config files that host the logfolder and connectionstrings loading. Can you take a look at that from the dump i attached earlier?

**Comment by AlenPelin** [comment]
Hi @rp-andre, I know what you are talking about and I thought that have already fixed this issue. So could you kindly provide fresh Diagnostics Toolset log files when the web.config contains all this stuff?

**Comment by rp-andre** [comment]
Here you go, attached. Let me know if you can resolve and I will try again.
[log.20160322.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Toolset/files/184636/log.20160322.txt)

**Comment by AlenPelin** [comment]
Thanks. It is clear now what is the problem, however it is not that easy to fix.

**Comment by rp-andre** [comment]
I'm not certain what you mean. What specifically do you mean by moving out the element?
Thanks for your help!

**Comment by AlenPelin** [comment]
Sorry, github ate some parts of text. 

So I can suggest to move the `<connectionStrings configSource>` element out of `<location>` if possible.

**Comment by AlenPelin** [comment]
The issue depends on https://github.com/Sitecore/Sitecore-Config-Builder/issues/11
